In [4]:
import os
import cv2

In [5]:
import numpy as np

In [6]:
os.listdir('images')

['emilia-clarke',
 'justin',
 'kit-harington',
 'nikolaj-coster-waldau',
 'peter-dinklage',
 'promit']

In [7]:
image_dir=os.listdir('C:/Users/PROMIT/Downloads/images')
src_path='C:/Users/PROMIT/Downloads/images'

In [8]:
image_dir

['emilia-clarke',
 'justin',
 'kit-harington',
 'nikolaj-coster-waldau',
 'peter-dinklage',
 'promit']

In [55]:
current_id=0
label_ids={}
y_labels=[]
x_train=[]

In [10]:
# Load the cascade
face_cascade = cv2.CascadeClassifier('C:/Users/PROMIT/Desktop/DFT/facehar.xml')

In [56]:
for root,dirs,files in os.walk(src_path):
    for file in files:
        if file.endswith("jpg") or file.endswith("jpg"):
            path=os.path.join(root,file)
            label=os.path.basename(root).replace(" ","-").lower()
            
            if label in label_ids:
                pass
            else:
                label_ids[label]=current_id
                current_id+=1
            id_=label_ids[label]
            final_image=pil_image.resize((500,500),Image.ANTIALIAS)
            print(label_ids)
            pil_image=Image.open(path).convert("L")
            image_array=np.array(pil_image,"uint8")
            print(image_array)
            faces=face_cascade.detectMultiScale(image_array,1.5,5)
            for (x,y,w,h) in faces:
                roi=image_array[y:y+h, x:x+w]
                x_train.append(roi)
                y_labels.append(id_)
                


{'emilia-clarke': 0}
[[189 191 191 ... 233 232 232]
 [189 191 193 ... 233 233 232]
 [191 191 192 ... 234 234 232]
 ...
 [135 137 142 ...  27  29  30]
 [131 135 140 ...  28  27  28]
 [129 132 135 ...  29  29  27]]
{'emilia-clarke': 0}
[[ 0  0  1 ...  3  4  4]
 [ 0  0  1 ...  3  4  4]
 [ 0  0  2 ...  3  4  4]
 ...
 [78 80 83 ... 15 15 15]
 [73 79 87 ... 15 15 15]
 [72 83 86 ... 21 16 16]]
{'emilia-clarke': 0}
[[184 185 185 ... 156 153 252]
 [184 184 185 ... 156 153 253]
 [184 184 184 ... 156 154 253]
 ...
 [191 191 190 ... 140 140 249]
 [196 196 195 ... 135 150 251]
 [190 190 190 ... 146 158 240]]
{'emilia-clarke': 0}
[[184 184 184 ... 123 117 116]
 [184 184 184 ... 126 119 117]
 [184 184 184 ... 130 122 119]
 ...
 [174 174 174 ... 108 108 108]
 [174 174 174 ... 108 108 108]
 [174 174 174 ... 108 108 108]]
{'emilia-clarke': 0}
[[58 60 60 ... 55 53 54]
 [62 61 60 ... 56 52 54]
 [62 56 60 ... 55 49 54]
 ...
 [44 40 42 ... 25 26 26]
 [42 41 43 ... 26 28 26]
 [43 40 40 ... 25 27 27]]
{'emili

In [59]:
recognizer.train(x_train,np.array(y_labels))
recognizer.save("trainner_finu.yml")

In [49]:
label_ids

{'emilia-clarke': 0,
 'justin': 1,
 'kit-harington': 2,
 'nikolaj-coster-waldau': 3,
 'peter-dinklage': 4,
 'promit': 5}

In [43]:
import PIL

In [35]:
y_labels

[0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4]

In [50]:
import pickle

In [57]:
with open("labels5.pickle",'wb') as f:
    pickle.dump(label_ids,f)

In [58]:
recognizer = cv2.face.LBPHFaceRecognizer_create()