<a href="https://colab.research.google.com/github/PromitHal/AI_ML/blob/main/mobile_price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import pandas as pd
dataset=pd.read_csv('mobile_train.csv')
dataset.head()

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [16]:
dataset.shape

(2000, 21)

**Splitting up dataset into Features and Targets**

In [19]:
X_dataset=dataset.drop(columns='price_range',axis=1)

In [21]:
X_dataset.head()

battery_power  blue  clock_speed  ...  three_g  touch_screen  wifi
0            842     0          2.2  ...        0             0     1
1           1021     1          0.5  ...        1             1     0
2            563     1          0.5  ...        1             1     0
3            615     1          2.5  ...        1             0     0
4           1821     1          1.2  ...        1             1     0

[5 rows x 20 columns]

In [20]:
Y_dataset=dataset['price_range']

In [22]:
Y_dataset.head()

0    1
1    2
2    2
3    2
4    1
Name: price_range, dtype: int64

**Changing pandas dataframe into numpy array**

In [4]:
Array_dataset=np.array(dataset)

In [24]:
X_dataset_array=np.array(X_dataset)

In [27]:
Y_dataset_array=np.array(Y_dataset)

**Normalizing the data**

In [28]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_dataset_standard=sc.fit_transform(X_dataset_array)

In [29]:
X_dataset_standard[1]

array([-0.49513857,  1.0100505 , -1.2530642 ,  0.98117712, -0.99289039,
        0.95788598,  1.15502422,  0.68754816, -0.12005944, -0.66476784,
       -0.64598879,  0.58577791,  1.70446468,  0.46731702,  1.11426556,
       -0.63531667, -0.73426721,  0.55964063,  0.99401789, -1.01409939])

In [32]:
from sklearn.preprocessing import OneHotEncoder
onhe=OneHotEncoder()


In [48]:
Y_dataset_array

array([1, 2, 2, ..., 3, 0, 3])

**Performing one hot encoding to create unique classes**

In [36]:
Y_dataset_array.size

2000

In [37]:
shape=(Y_dataset_array.size,Y_dataset_array.max()+1)

In [38]:
one_hot_encoded=np.zeros(shape)

In [42]:
one_hot_encoded.shape

(2000, 4)

In [50]:
for i in range(len(Y_dataset_array)):
  x=Y_dataset_array[i]
  for j in range(4):
    if(j==x):
      one_hot_encoded[i][j]=1
    else:
      one_hot_encoded[i][j]=0


    

In [53]:
one_hot_encoded[1999]

array([0., 0., 0., 1.])

**Splitting datset into train and test**

In [54]:
from sklearn.model_selection import train_test_split 
X_train,X_test,Y_train,Y_test=train_test_split(X_dataset_standard,one_hot_encoded,test_size=0.1)

**Building our Neural Network**

In [55]:
import tensorflow as tf
from tensorflow.keras.models import Sequential 
from keras.layers import Dense


In [56]:
model=Sequential()
model.add(Dense(16,input_dim=20,activation='relu'))
model.add(Dense(14,activation='relu'))
model.add(Dense(4,activation='softmax'))

**Compiling the model**

In [57]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [59]:
history=model.fit(X_train,Y_train,epochs=100,batch_size=64)

Epoch 1/100
29/29 [==============================] - 1s 2ms/step - loss: 1.3567 - accuracy: 0.3528
Epoch 2/100
29/29 [==============================] - 0s 2ms/step - loss: 1.2645 - accuracy: 0.4233
Epoch 3/100
29/29 [==============================] - 0s 2ms/step - loss: 1.1880 - accuracy: 0.4767
Epoch 4/100
29/29 [==============================] - 0s 2ms/step - loss: 1.1088 - accuracy: 0.5250
Epoch 5/100
29/29 [==============================] - 0s 2ms/step - loss: 1.0272 - accuracy: 0.5528
Epoch 6/100
29/29 [==============================] - 0s 2ms/step - loss: 0.9487 - accuracy: 0.5939
Epoch 7/100
29/29 [==============================] - 0s 2ms/step - loss: 0.8738 - accuracy: 0.6294
Epoch 8/100
29/29 [==============================] - 0s 2ms/step - loss: 0.8035 - accuracy: 0.6661
Epoch 9/100
29/29 [==============================] - 0s 2ms/step - loss: 0.7387 - accuracy: 0.7128
Epoch 10/100
29/29 [==============================] - 0s 2ms/step - loss: 0.6800 - accuracy: 0.7444
Epoch 11/

**Checking performance on test data**

In [61]:
y_pred=model.predict(X_test)
pred=list()
for i in range(len(y_pred)):
  pred.append(np.argmax(y_pred[i]))
test=list()
for i in range(len(Y_test)):
  test.append(np.argmax(Y_test[i]))

In [63]:
from sklearn.metrics import accuracy_score 
a=accuracy_score(pred,test)
print('Accuracy score for our model is :',a*100)

Accuracy score for our model is : 92.5
